<#
.SYNOPSIS
    Creates the Set it Free label taxonomy in a GitHub repository.

.DESCRIPTION
    Sets up all agent lifecycle, risk-class, and intake-source labels required
    by the Set it Free governance policy (docs/SET_IT_FREE_GOVERNANCE.md).

    Idempotent: updates existing labels rather than failing on duplicates.

.PARAMETER Owner
    GitHub org or user that owns the target repository.

.PARAMETER Repo
    Repository name.

.PARAMETER DryRun
    Print what would be done without making any API calls.

.EXAMPLE
    .\setup-github-labels.ps1 -Owner HemSoft -Repo hs-buddy
    .\setup-github-labels.ps1 -Owner HemSoft -Repo hs-buddy -DryRun
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [string] $Owner,

    [Parameter(Mandatory)]
    [string] $Repo,

    [switch] $DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ─── Label definitions ────────────────────────────────────────────────────────

$Labels = @(
    # ── Lifecycle labels ──────────────────────────────────────────────────────
    @{ name = "agent:fixable";           color = "2ea44f"; description = "Agent has analyzed this and can auto-fix safely" }
    @{ name = "agent:in-progress";       color = "0075ca"; description = "Agent is actively working on this item" }
    @{ name = "agent:review-requested";  color = "d4af37"; description = "Agent completed work; requesting human review" }
    @{ name = "agent:pause";             color = "e3771a"; description = "Agent halted; issue needs human intervention before retry" }
    @{ name = "agent:human-required";    color = "d73a4a"; description = "Fix exceeds safe automation boundary — human must own this" }
    @{ name = "agent:escalated";         color = "b60205"; description = "Escalated after repeated failures; senior review needed" }

    # ── Risk-class labels ─────────────────────────────────────────────────────
    @{ name = "risk:trivial";  color = "cfd3d7"; description = "Zero-risk: formatting, typos, doc updates" }
    @{ name = "risk:low";      color = "0e8a16"; description = "Low-risk: dependency bumps, safe refactors" }
    @{ name = "risk:medium";   color = "fbca04"; description = "Medium-risk: logic changes, new features" }
    @{ name = "risk:high";     color = "e11d48"; description = "High-risk: auth, payments, data migrations" }
    @{ name = "risk:critical"; color = "6f1b1b"; description = "Critical: security, PII, compliance-adjacent" }

    # ── Intake-source labels ──────────────────────────────────────────────────
    @{ name = "source:repo-audit";    color = "bfd4f2"; description = "Generated by repo-audit skill" }
    @{ name = "source:jira";          color = "0052cc"; description = "Normalized from Jira ticket" }
    @{ name = "source:github-issue";  color = "6f42c1"; description = "Created from an existing GitHub issue" }
    @{ name = "source:manual";        color = "f9f1a5"; description = "Manually created by developer" }

    # ── Type labels ───────────────────────────────────────────────────────────
    @{ name = "type:report";      color = "8b949e"; description = "Informational output only — automation must not act on this" }
    @{ name = "type:action-item"; color = "1f6feb"; description = "Actionable item — automation will process and generate a PR" }

    # ── Opt-out label ─────────────────────────────────────────────────────────
    @{ name = "no-agent"; color = "ffffff"; description = "Opt this issue out of all Set it Free automation" }
)

# ─── Helpers ──────────────────────────────────────────────────────────────────

function Write-Status([string]$Emoji, [string]$Message, [ConsoleColor]$Color = "Cyan") {
    Write-Host "$Emoji  $Message" -ForegroundColor $Color
}

function Get-GhToken {
    $token = & gh auth token 2>$null
    if (-not $token) {
        throw "GitHub CLI is not authenticated. Run 'gh auth login' first."
    }
    return $token
}

function Invoke-GhApi {
    param(
        [string] $Method,
        [string] $Endpoint,
        [hashtable] $Body
    )

    $args = @("api", "--method", $Method, $Endpoint)
    if ($Body) {
        foreach ($key in $Body.Keys) {
            $args += @("-f", "$key=$($Body[$key])")
        }
    }

    $result = & gh @args 2>&1
    $exitCode = $LASTEXITCODE

    return @{ ExitCode = $exitCode; Output = $result }
}

function Get-ExistingLabels {
    $response = & gh api "repos/$Owner/$Repo/labels" --paginate 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to list labels: $response"
    }
    return ($response | ConvertFrom-Json) | ForEach-Object { $_.name }
}

# ─── Main ─────────────────────────────────────────────────────────────────────

Write-Status "🏷️" "Set it Free — GitHub Label Setup" White
Write-Status "📦" "Target: $Owner/$Repo"

if ($DryRun) {
    Write-Status "🔍" "DRY RUN — no changes will be made" Yellow
}

# Verify gh CLI is available
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "GitHub CLI (gh) is not installed. Install via: winget install GitHub.cli"
    exit 1
}

# Fetch existing labels
Write-Status "📋" "Fetching existing labels…"
try {
    $existing = Get-ExistingLabels
    Write-Status "✅" "Found $($existing.Count) existing label(s)"
} catch {
    Write-Error $_
    exit 1
}

$created = 0
$updated = 0
$skipped = 0
$failed  = 0

foreach ($label in $Labels) {
    $name   = $label.name
    $color  = $label.color
    $desc   = $label.description
    $exists = $existing -contains $name

    if ($DryRun) {
        $action = if ($exists) { "UPDATE" } else { "CREATE" }
        Write-Status "🔍" "[$action] $name (#$color)"
        continue
    }

    try {
        if ($exists) {
            # PATCH to update color/description
            $result = Invoke-GhApi -Method PATCH `
                -Endpoint "repos/$Owner/$Repo/labels/$([uri]::EscapeDataString($name))" `
                -Body @{ color = $color; description = $desc }

            if ($result.ExitCode -eq 0) {
                Write-Status "✏️ " "Updated:  $name" Green
                $updated++
            } else {
                Write-Status "❌" "Failed to update $name`: $($result.Output)" Red
                $failed++
            }
        } else {
            # POST to create
            $result = Invoke-GhApi -Method POST `
                -Endpoint "repos/$Owner/$Repo/labels" `
                -Body @{ name = $name; color = $color; description = $desc }

            if ($result.ExitCode -eq 0) {
                Write-Status "✅" "Created:  $name" Green
                $created++
            } else {
                Write-Status "❌" "Failed to create $name`: $($result.Output)" Red
                $failed++
            }
        }
    } catch {
        Write-Status "❌" "Error on $name`: $_" Red
        $failed++
    }
}

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "─────────────────────────────────────────" -ForegroundColor DarkGray
if ($DryRun) {
    Write-Status "🔍" "Dry run complete. $($Labels.Count) label(s) would be processed." Yellow
} else {
    Write-Status "📊" "Created: $created  |  Updated: $updated  |  Skipped: $skipped  |  Failed: $failed"
    if ($failed -gt 0) {
        Write-Status "⚠️ " "$failed label(s) failed. Check output above." Yellow
        exit 1
    } else {
        Write-Status "🎉" "Done! View labels at: https://github.com/$Owner/$Repo/labels" Green
    }
}
